server:
  port: 80

spring:
  mail:
    host: smtp.qq.com
    username: 22@qq.com
    password: kyzmlvyuvifmecga
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          required: true



